### ISSUE TITLE
Removes the shebang line

### ISSUE THREAD

**Issue by bahmutov** [thlorenz/cardinal#10]
Hi,

Great project, works pretty robustly. I am using to output highlighted javascript or json file in the center of the terminal in [center-code](https://github.com/bahmutov/center-code). I noticed that shebang line if it is the first one is handled, but it is removed from the output. Thus something like this

```
#!/usr/bin/env node

var foo = 42;
```

will be highlighted but simply as

```

var foo = 42;
```

**Comment by thlorenz** [comment]
Yeah we had to remove that line since that used to break the highlighter.
However thanks to the latest changes by @ariya it is more forgiving now.
Do you think we could keep it in, i.e. when `buildAst == false` @ariya?

**Comment by ariya** [comment]
I file this as https://github.com/thlorenz/redeyed/issues/14.

**Comment by ariya** [comment]
With the updated `redeyed` and the latest version (tested with Cardinal 2.1.1), it now works as expected.
