### ISSUE TITLE
Cannot handle object spread syntax

### ISSUE THREAD

**Issue by hummlas** [thlorenz/cardinal#16]
I know that technically object spread is only a stage 2 proposal on the ECMAscript standard, but it would be lovely if cardinal could handle it :)

It doesn't have to highlight it, just not crash with an exception when it's encountered (`Unexpected token ...`)

https://github.com/sebmarkbage/ecmascript-rest-spread

**Comment by ariya** [comment]
Solved with PR #18:

![image](https://cloud.githubusercontent.com/assets/7288/18117201/eebeb120-6f01-11e6-91eb-a5b5a11528b6.png)
