### ISSUE TITLE
Docked

### ISSUE THREAD

**Issue by giftig** [thlorenz/cardinal#27]
Hi, just pointing out that since I found cardinal pretty handy for prettifying JSON in some of my scripts but I didn't want to try to package my scripts with the dependency on node and cardinal, I threw this together:

https://github.com/giftig/docker-cardinal

If having a docker quickstart for cardinal is something that's of interest to you, I'd like to contribute it. It's pretty rough but does the job. I stuck an image in https://hub.docker.com/r/giftig/cardinal/

**Comment by thlorenz** [comment]
Nice, we could add a link to the readme.
Mind doing a PR to do that?
