### ISSUE TITLE
Can't colorize JavaScript with syntax errors.

### ISSUE THREAD

**Issue by bucaran** [thlorenz/cardinal#7]
I was trying to super colorize a console error stack trace code part of the message and run into `cardinal` which seemed great for colorizing valid JS, but fails if:

```
 Unable to perform highlight. The code contained syntax errors:
```

Kind of ironic. Too bad.

###### Related
+  #1

**Comment by thlorenz** [comment]
Yeah, sorry it has to be parseable.
I'm not aware of a terminal highlighter that doesn't need to fully parse JS.
If you find one please LMK and I'll add it to the readme as an alternative.
