### ISSUE TITLE
Suppor ES6 syntax

### ISSUE THREAD

**Issue by gajus** [thlorenz/cardinal#8]
Unfortunately cardinal does not seem to be able to recognise most of the ES6 syntax.

<img width="608" alt="screen shot 2015-09-03 at 20 52 36" src="https://cloud.githubusercontent.com/assets/973543/9669218/bbb10108-527d-11e5-99a4-30990ffbdf0d.png">

**Comment by ThibWeb** [comment]
Hey @gajus, support seems to have been introduced in the `0.5.0` release. Maybe give this one a try?

Here's a before/after 0.5: https://github.com/firede/msee/pull/14

**Comment by thlorenz** [comment]
0.6 [added even more keywords](https://github.com/thlorenz/cardinal/commit/3bde9f571e109fd31ccee906bc644ea73d923e24)
